---
- name: Ansible for AWS, creating VPC
  hosts: localhost
  connection: local

  vars:
    this_name: aabeginner
    aws_region: ap-southeast-2
    awsvpc_vpc_cidr_block: "10.10.0.0/16"
    owner: adevopsbeginner

  vars_files:
    - vault.yml

  environment:
    AWS_REGION: "{{ aws_region }}"
    AWS_ACCESS_KEY: '{{ vault_aws_access_key }}'
    AWS_SECRET_KEY: '{{ vault_aws_secret_key }}'

  tasks:
    - name: New a VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ this_name }}"
        state: present
        region: "{{ aws_region }}"
        cidr_block: "{{ awsvpc_vpc_cidr_block }}"
        dns_hostnames: true
        dns_support: true
        tags:
          Name: "{{ this_name }}"
          owner: "{{ owner }}"
        tenancy: default

