---
- name: Ansible Playbook for AWS Automation - EC2
  hosts: localhost
  connection: local

  vars:
    #this_name: a_ansible
    aws_region: ap-southeast-2
    ami_name_prefix: al2023-ami-2023
    instance_type: t3.micro
    volume_size: 32
    keypair_name: "a_abeginner_ed25519"
    public_subnet_id: subnet-03438a3c5ba878bbf
    ec2sg_id: sg-078cdfac5d06e93c0

  vars_files:
    - vault.yml

  environment:
    AWS_REGION: "{{ aws_region }}"
    AWS_ACCESS_KEY: '{{ vault_aws_access_key }}'
    AWS_SECRET_KEY: '{{ vault_aws_secret_key }}'

  tasks:
    - name: Get AMI id
      amazon.aws.ec2_ami_info:
        filters:
          name: "{{ ami_name_prefix }}*"
          architecture: "x86_64"
      register: ec2ami
    
    - name: Get lastest AMI
      ansible.builtin.set_fact:
        sorted_ami_list: "{{ ec2ami.images | sort(attribute='creation_date', reverse=true) }}"

    - name: New EC2 instance - {{ this_name }}
      amazon.aws.ec2_instance:
        name: "{{ this_name }}"
        vpc_subnet_id: "{{ public_subnet_id }}"
        image_id: "{{ sorted_ami_list[0].image_id }}"
        key_name: "{{ keypair_name }}"
        security_group: "{{ ec2sg_id }}"
        instance_type: "{{ instance_type }}"
        wait: true
        wait_timeout: 60
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: "{{ volume_size }}"
              delete_on_termination: false
        termination_protection: false
        network:
          assign_public_ip: true
        tags:
          Name: "{{ this_name }}"
          owner: "{{ owner }}"
          repo: "{{ repo }}"
      # loop:
      #   - webservera
      #   - webserverb
      #   - database1
      #   - db_postgres
      #   - ansible
      #   - sydney
      #   - friday
      #   - apache
      #   - httpd
      #   - the-tenth-server
      # loop_control:
      #   loop_var: this_name
        