---
  - name: Delete k8s namespaces
    kubernetes.core.k8s:
      name: '{{ item }}'
      api_version: v1
      kind: Namespace
      state: absent
    loop:
      #- cattle-system
      - grafana
      - postgres
      - cert-manager
      - ingress-nginx
      - traefik
      - "{{ my_application }}"
    ignore_errors: true

  - name: Terraform eks
    community.general.terraform:
      project_path: '{{ code_base }}/terraform/eks'
      state: '{{ deploy_state }}'
      workspace: '{{ eks_cluster_name }}'
      init_reconfigure: yes
      backend_config:
        region:         "ap-southeast-2"
        bucket:         "ansible-terraform-eks-states"
        dynamodb_table: "ansible_terraform_eks_state"
        key:            "eks-cluster-{{ eks_cluster_name }}.tfstate"
        profile:        '{{ aws_profile }}'
    environment:
      TF_VAR_aws_profile: '{{ aws_profile }}'
      TF_VAR_aws_account_no: '{{ aws_account_no }}'
      TF_VAR_aws_region: '{{ aws_region }}'
      TF_VAR_this_name: '{{ eks_cluster_name }}'
    register: result

  - name: Terraform logs
    debug:
      msg: '{{ result.stdout_lines }}'

  - name: Update kubeconfig
    command: aws eks update-kubeconfig --name {{ eks_cluster_name }}-cluster --profile {{ aws_profile }} --region {{ aws_region }}
    when: deploy_state == 'present'
