---
- name: Playbook - how to create an ansible role
  hosts: all
  vars:
    new_hostname: uno

  roles:
    - hostname

  tasks:
    - name: Show hostname
      ansible.builtin.debug:
        var: ansible_hostname
