---
- name: Playbook - show hostname
  hosts: all

  tasks:
    - name: Show hostname
      ansible.builtin.debug:
        var: ansible_hostname

    - name: Show fqdn
      ansible.builtin.debug:
        var: ansible_fqdn

    - name: Set hostname
      ansible.builtin.hostname:
        name: "uno"
      become: yes

